# 팀원 이름 설정
[people]
names = [
    "박홍",
    "손양현",
    "김예원",
    "서하준",
    "장준성",
    "차광은",
    "송준영",
    "김문석",
    "목은준",
    "이축복",
    "박지훈",
    "김계린",
    "최윤석",
    "김영준",
    "김현수",
    "오세영",
    "유제혁",
    "박문혁",
    "김수민",
    "박예은",
    "공지현",
    "김지현",
    "안정연",
    "이예나",
    "옥진주",
    "이송희",
    "유규리",
    "전재희",
    "이웅지",
    "장혜진",
    "서지우",
    "정하연",
    "이한나",
    "김소현",
    "이한솔",
    "강태건",
    "이은총",
    "김혜린",
    "조은정",
    "김민구",
    "김현정",
    "김주헌",
    "채윤정",
    "조영준",
]

# 기본 설정
[default]
n_people = 45
num_teams = 9
team_size = 5
distribution_type = "불균등"
